### PR TITLE
changed from named_scope to scope

### PR DESCRIPTION
**Pull request by Pasta**
To be rails 3 compliant.

Cheers,

### CODE REVIEW

**Comment by paulca** [comment]
Hmmmm ... does the gem even work with Rails 3? I haven't tested it or got it working with Rails 3 ...

**Comment by raid5** [comment]
It will take more than this to port it over to Rails3, but it is a step in the right direction.

**Comment by Pasta** [comment]
Actually you're right, doesn't work anyway. 

I rewrote it from scratch in order for it to work with rails 3, great inspiration from your code though.

**Comment by paulca** [comment]
Awesome! I've converted / rewritten a few plugins lately for Rails 3. I'll definitely port paths_to_glory if I need to in the coming months : it's definitely not too crazy a job.

**Comment by Pasta** [comment]
here is the gem: https://github.com/Pasta/badgr

Enjoy. I see a lot of room for improvement. I'm using it for a application i'm working on, so i'll improve it through time!

**Comment by raid5** [comment]
@paulca you can checkout my rails3 branch of your paths_of_glory if you want. Used it in a couple rails3 projects already.

**Pull request closed without merging**
